baseurl = "/"
theme = "hello-friend-ng"
languageCode = "en-us"


title = "Syarip Muhammad Abdillah"

paginate = 100
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[taxonomies]
  tag = "tags"
  
[params]
  dateform = "Jan 2, 2006"
  dateformShor = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  DefaultContentLanguage = "en"
  description = "Personal Website"
  keywords = "DevSecOps, DevOps, Cloud, etc."
  images = [""]

  homeSubtitle = ""
  feedUrl = ""

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

  [params.logo]
    logoText = "syarifabdillah.my.id"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "email"
    url = "mailto:abdillahsyarip@gmail.com"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/syarifabdillah13"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/syarifabdillah13/"

[menu]
  [[menu.main]]
    identifier = "Docs"
    name = "Documentation"
    url = "/posts"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"