baseurl = "https://syarifabdillah.my.id"
theme = "hello-friend-ng"
languageCode = "en-us"
googleAnalytics = "G-P4ZZQCL6M2"

title = "Syarip Muhammad Abdillah"

paginate = 100
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[taxonomies]
  tag = "tags"
  
[params]
  dateform = "Jan 2, 2006"
  dateformShor = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  DefaultContentLanguage = "en"
  description = "Homepage and microblog by Syarip Muhammad Abdillah"
  keywords = "DevSecOps, DevOps, Cloud Computing, etc."
  images = [""]

  homeSubtitle = "Systems Engineer"
  feedUrl = ""

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "light"

  [params.logo]
    logoText = "> $ cd ~"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "email"
    url = "mailto:abdillahsyarip@gmail.com"

  [[params.social]]
    name = "github"
    url = "https://github.com/sectenzorg"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/syarifabdillah13/"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/_syarifabdillah"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    url = "/posts"

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
